        </div>
      </main>
    </div>

    <dialog class="mdl-dialog" id="full-width-dialog">
      <h4 class="mdl-dialog__title"></h4>
      <div class="mdl-dialog__content">
      </div>
      <div class="mdl-dialog__actions">
        <button type="button" class="mdl-button close">CLOSE</button>
      </div>
    </dialog>

    <script type="text/javascript" src="<?php echo $root_uri; ?>/assets/js/libraries.js"></script>
  </body>
</html>
